---
- name: Check MySQL Server Health
  hosts: 10.112.0.9
  gather_facts: no
  vars:
    mysql_host: "{{mysql_host}}"
    mysql_user: "{{mysql_user}}"
    mysql_password: "{{mysql_password}}"
    mysql_database: "{{mysql_database}}"
    mysql_port: "{{mysql_port}}"

  tasks:
    - name: Get Database Space Utilization
      shell: |
        mysql -h {{ mysql_host }} -u {{ mysql_user }} -p{{ mysql_password }} -P {{ mysql_port }} -D {{ mysql_database }} -e "SELECT table_schema AS DatabaseName, SUM(data_length + index_length) / 1024 / 1024 AS SizeMB FROM information_schema.tables WHERE table_schema != 'information_schema' GROUP BY table_schema;"
      register: db_space
      ignore_errors: yes

    - name: Get Database Health
      shell: |
        mysql -h {{ mysql_host }} -u {{ mysql_user }} -p{{ mysql_password }} -P {{ mysql_port }} -D {{ mysql_database }} -e "SELECT schema_name, default_character_set_name, default_collation_name FROM information_schema.schemata;"
      register: db_health
      ignore_errors: yes

    - name: Check for Deadlocks
      shell: |
        mysql -h {{ mysql_host }} -u {{ mysql_user }} -p{{ mysql_password }} -P {{ mysql_port }} -D {{ mysql_database }} -e "SHOW ENGINE INNODB STATUS;"
      register: deadlocks
      ignore_errors: yes

    - name: Get MySQL Process List
      shell: |
        mysql -h {{ mysql_host }} -u {{ mysql_user }} -p{{ mysql_password }} -P {{ mysql_port }} -D {{ mysql_database }} -e "SHOW PROCESSLIST;"
      register: process_list
      ignore_errors: yes

    - name: Display Results
      debug:
        msg:
          - "Database Space Utilization: {{ db_space.stdout | default('No output') }}"
          - "Database Health: {{ db_health.stdout | default('No output') }}"
          - "Deadlocks: {{ deadlocks.stdout | default('No output') }}"
          - "MySQL Process List: {{ process_list.stdout | default('No output') }}"
