---
- name: Check MySQL Database Space
  hosts: my_servers
  become: yes  # If needed to use sudo privileges
  vars:
    mysql_user: "{{mysql_user}}"
    mysql_password: "{{ mysql_password }}"  # Use an Ansible variable for security

  tasks:
    - name: Ensure MySQL client is installed
      package:
        name: mysql-client
        state: present

    - name: Get database space usage via MySQL command
      command: >
        mysql -u{{ mysql_user }} -p{{ mysql_password }} -e "SELECT table_schema AS 'Database',
                        SUM(data_length + index_length) / 1024 / 1024 AS 'Size (MB)' 
                 FROM MYSQLSV.tables 
                 GROUP BY table_schema;"
      register: db_space_output

    - name: Show database sizes
      debug:
        msg: "{{ db_space_output.stdout_lines }}"
