---
- name: MySQL Database Health Check
  hosts: localhost
  become: no
  vars:
    mysql_host: "{{mysql_host}}"
    mysql_user: "{{mysql_user}}"
    mysql_password: "{{mysql_password}}"
    mysql_db: "{{mysql_db}}"
    mysql_port: "{{mysql_port}}"

  tasks:
    - name: Check MySQL Database Space Utilization
      community.mysql.mysql_query:
        login_host: "{{ mysql_host }}"
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
        db: "{{ mysql_db }}"
        port: "{{ mysql_port }}"
        query: |
          SELECT table_schema AS 'Database',
                 ROUND(SUM(data_length + index_length) / 1024 / 1024, 2) AS 'Size (MB)'
          FROM information_schema.tables
          GROUP BY table_schema;
      register: db_space

    - name: Display MySQL DB Space Utilization
      debug:
        var: db_space

    - name: Check MySQL DB Health (Server Status)
      community.mysql.mysql_query:
        login_host: "{{ mysql_host }}"
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
        db: "{{ mysql_db }}"
        port: "{{ mysql_port }}"
        query: |
          SHOW STATUS WHERE `variable_name` = 'Uptime';
      register: db_health

    - name: Display MySQL DB Health
      debug:
        var: db_health

    - name: Check for Deadlocks in MySQL
      community.mysql.mysql_query:
        login_host: "{{ mysql_host }}"
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
        db: "{{ mysql_db }}"
        port: "{{ mysql_port }}"
        query: |
          SHOW ENGINE INNODB STATUS;
      register: deadlocks

    - name: Display Deadlocks Information
      debug:
        var: deadlocks

    - name: Check Active Jobs (Running Queries)
      community.mysql.mysql_query:
        login_host: "{{ mysql_host }}"
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
        db: "{{ mysql_db }}"
        port: "{{ mysql_port }}"
        query: |
          SHOW FULL PROCESSLIST;
      register: active_jobs

    - name: Display Active Jobs
      debug:
        var: active_jobs
