---
- name: Check MySQL Database Health and Space Utilization
  hosts: mysql_servers  # Define your target MySQL server group
  become: true
  tasks:

    - name: Check MySQL server space utilization
      shell: df -h /var/lib/mysql
      register: disk_space
      changed_when: false

    - name: Print MySQL server disk space
      debug:
        msg: "Disk space used on MySQL server: {{ disk_space.stdout }}"

    - name: Check MySQL database space utilization
      mysql_db:
        login_user: "root"
        login_password: "mysqlAutomation"
        login_host: "localhost"
        name: "{{ mysql_db }}"
        state: 'query'
        query: "SELECT table_schema, SUM(data_length + index_length) / 1024 / 1024 AS db_size_mb FROM MYSQLSV.tables GROUP BY table_schema;"
      register: db_space_utilization
      changed_when: false

    - name: Print database space utilization
      debug:
        msg: "Database space utilization: {{ db_space_utilization.stdout }}"

    - name: Check MySQL database health status
      mysql_db:
        login_user: "root"
        login_password: "mysqlAutomation"
        login_host: "localhost"
        name: "MYSQLSV"
        state: 'query'
        query: "SHOW GLOBAL STATUS LIKE 'Threads_connected';"
      register: db_health_status
      changed_when: false

    - name: Print MySQL health status
      debug:
        msg: "Current MySQL server health status: {{ db_health_status.stdout }}"
