---
- name: MySQL Server Health Check
  hosts: localhost
  become: true
  gather_facts: no
  vars:
    mysql_host: "{{mysql_host}}"
    mysql_user: "{{mysql_user}}"
    mysql_password: "{{mysql_password}}"
    mysql_db: "{{mysql_db}}"
    mysql_port: "{{mysql_port}}"

  tasks:
    - name: Check MySQL database space utilization
      shell: |
        mysql -h "{{ mysql_host }}" -u "{{ mysql_user }}" -p"{{ mysql_password }}" -D "{{ mysql_db }}" -e "
        SELECT table_schema AS DatabaseName,
               SUM(data_length + index_length) / 1024 / 1024 AS TotalSizeMB
        FROM information_schema.tables
        GROUP BY table_schema;"
      register: db_space
      changed_when: false

    - name: Display database space utilization
      debug:
        msg: |
          {% for row in db_space.stdout_lines[1:] %}
          - {{ row.split("\t")[0] }}: {{ row.split("\t")[1] }} MB
          {% endfor %}

    - name: Check for deadlocks in MySQL
      shell: |
        mysql -h "{{ mysql_host }}" -u "{{ mysql_user }}" -p"{{ mysql_password }}" -D "{{ mysql_db }}" -e "SHOW ENGINE INNODB STATUS;"
      register: deadlocks
      changed_when: false

    - name: Display deadlocks status
      debug:
        msg: |
          {% if "LATEST DETECTED DEADLOCK" in deadlocks.stdout %}
            Deadlock detected: {{ deadlocks.stdout | regex_search('LATEST DETECTED DEADLOCK.*') }}
          {% else %}
            No deadlocks detected
          {% endif %}

    - name: Check MySQL event scheduler activities
      shell: |
        mysql -h "{{ mysql_host }}" -u "{{ mysql_user }}" -p"{{ mysql_password }}" -D "{{ mysql_db }}" -e "
        SELECT event_name, status
        FROM information_schema.events
        WHERE status = 'ENABLED';"
      register: job_activities
      changed_when: false

    - name: Display event scheduler activities
      debug:
        msg: |
          {% if job_activities.stdout_lines | length > 1 %}
            {% for event in job_activities.stdout_lines[1:] %}
            - Event: {{ event.split("\t")[0] }} | Status: {{ event.split("\t")[1] }}
            {% endfor %}
          {% else %}
            No active events found.
          {% endif %}

    - name: Check MySQL database health (Active connections)
      shell: |
        mysql -h "{{ mysql_host }}" -u "{{ mysql_user }}" -p"{{ mysql_password }}" -D "{{ mysql_db }}" -e "SHOW STATUS LIKE 'Threads_connected';"
      register: db_health
      changed_when: false

    - name: Display database health status
      debug:
        msg: |
          Active Connections: {{ db_health.stdout_lines[1].split("\t")[1] }}
