---
- name: MySQL Server Health Check
  hosts: 10.112.0.10
  become: true
  vars:
    mysql_host: "{{mysql_host}}"
    mysql_database: "{{mysql_database}}"
    mysql_username: "{{mysql_username}}"
    mysql_password: "{{mysql_password}}"
    mysql_port: "{{mysql_port}}"

  tasks:

    - name: Ensure MySQL Python module is installed
      pip:
        name: mysql-connector-python
        state: present

    - name: Check MySQL Database Space Utilization
      community.mysql.mysql_query:
        login_host: "{{ mysql_host }}"
        login_user: "{{ mysql_username }}"
        login_password: "{{ mysql_password }}"
        login_db: "{{ mysql_database }}"
        query: |
          SELECT table_schema AS DatabaseName,
                 SUM(data_length + index_length) / 1024 / 1024 AS TotalSizeMB
          FROM information_schema.tables
          GROUP BY table_schema;
      register: db_space_result
      ignore_errors: yes

    - name: Display Database Space Utilization
      debug:
        msg: "{{ db_space_result.results }}"

    - name: Check for Deadlocks
      community.mysql.mysql_query:
        login_host: "{{ mysql_host }}"
        login_user: "{{ mysql_username }}"
        login_password: "{{ mysql_password }}"
        login_db: "{{ mysql_database }}"
        query: SHOW ENGINE INNODB STATUS;
      register: deadlock_result
      ignore_errors: yes

    - name: Check if Deadlock Detected
      debug:
        msg: |
          {% if 'LATEST DETECTED DEADLOCK' in deadlock_result.results[0]['Value'] %}
            Deadlock detected: {{ deadlock_result.results[0]['Value'] }}
          {% else %}
            No deadlocks detected
          {% endif %}

    - name: Check MySQL Event Activities
      community.mysql.mysql_query:
        login_host: "{{ mysql_host }}"
        login_user: "{{ mysql_username }}"
        login_password: "{{ mysql_password }}"
        login_db: "{{ mysql_database }}"
        query: |
          SELECT event_name, status
          FROM information_schema.events
          WHERE status = 'ENABLED';
      register: event_activities
      ignore_errors: yes

    - name: Display Event Activities
      debug:
        msg: |
          {% if event_activities.results %}
            MySQL Event Activities:
            {% for row in event_activities.results %}
              - Event: {{ row.event_name }} | Status: {{ row.status }}
            {% endfor %}
          {% else %}
            No active events found.
          {% endif %}

    - name: Check MySQL Database Health (Threads Connected)
      community.mysql.mysql_query:
        login_host: "{{ mysql_host }}"
        login_user: "{{ mysql_username }}"
        login_password: "{{ mysql_password }}"
        login_db: "{{ mysql_database }}"
        query: SHOW STATUS LIKE 'Threads_connected';
      register: db_health_result
      ignore_errors: yes

    - name: Display MySQL Health Status
      debug:
        msg: |
          - Active Connections: {{ db_health_result.results[0].Value }}

    - name: Execute Remote MySQL Command (via SSH)
      ansible.builtin.shell: |
        mysql --host={{ mysql_host }} --user={{ mysql_username }} --password={{ mysql_password }} -e 'SELECT VERSION();'
      register: mysql_version_result
      ignore_errors: yes

    - name: Display MySQL Version (via SSH)
      debug:
        msg: "{{ mysql_version_result.stdout }}"
