---
- name: MySQL Server Health Check
  hosts: localhost
  gather_facts: no
  vars:
    mysql_host: "{{mysql_host}}"
    mysql_user: "{{mysql_user}}"
    mysql_password: "{{mysql_password}}"
    mysql_db: "{{mysql_db}}"
    mysql_port: "{{mysql_port}}"

  tasks:

    - name: Check MySQL database space utilization
      community.mysql.mysql_db:
        login_host: "{{ mysql_host }}"
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
        db: "{{ mysql_db }}"
        query: |
          SELECT table_schema AS DatabaseName,
                 SUM(data_length + index_length) / 1024 / 1024 AS TotalSizeMB
          FROM information_schema.tables
          GROUP BY table_schema;
      register: db_space

    - name: Display database space utilization
      debug:
        msg: |
          {% for row in db_space.query_result %}
          - {{ row.DatabaseName }}: {{ row.TotalSizeMB }} MB
          {% endfor %}

    - name: Check for deadlocks in MySQL
      community.mysql.mysql_db:
        login_host: "{{ mysql_host }}"
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
        db: "{{ mysql_db }}"
        query: "SHOW ENGINE INNODB STATUS;"
      register: deadlocks

    - name: Display deadlocks status
      debug:
        msg: |
          {% if "LATEST DETECTED DEADLOCK" in deadlocks.query_result[0]['Status'] %}
            Deadlock detected: {{ deadlocks.query_result[0]['Status'] }}
          {% else %}
            No deadlocks detected
          {% endif %}

    - name: Check MySQL event scheduler activities
      community.mysql.mysql_db:
        login_host: "{{ mysql_host }}"
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
        db: "{{ mysql_db }}"
        query: |
          SELECT event_name, status
          FROM information_schema.events
          WHERE status = 'ENABLED';
      register: job_activities

    - name: Display event scheduler activities
      debug:
        msg: |
          {% if job_activities.query_result %}
            {% for event in job_activities.query_result %}
            - Event: {{ event.event_name }} | Status: {{ event.status }}
            {% endfor %}
          {% else %}
            No active events found.
          {% endif %}

    - name: Check MySQL database health (Active connections)
      community.mysql.mysql_db:
        login_host: "{{ mysql_host }}"
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
        db: "{{ mysql_db }}"
        query: "SHOW STATUS LIKE 'Threads_connected';"
      register: db_health

    - name: Display database health status
      debug:
        msg: |
          Active Connections: {{ db_health.query_result[0]['Value'] }}
