- name: Fetch Pending ServiceNow Requests
  hosts: localhost
  gather_facts: no
  vars:
    servicenow_instance: "https://dev247928.service-now.com"
    servicenow_username: "admin"
    servicenow_password: "%ml4Vs9RXE/s"
    servicenow_table: "sc_request"
    tenant_id: "195e8969-c853-47b4-83d0-36e044d83923"
    client_id: "e2e46ae3-2dee-4eed-a074-ddffd760ab2b"
    client_secret: "PQZ8Q~XSmMsU4dbgk2KyWMHK1h8X7ciD~H.1_csi"
    default_user_email: "vidya@domain.com"
    default_user_name: "VidyaRa"
    default_mail_nickname: "vidya"
    domain_name: "amitomar63gmail.onmicrosoft.com"
    graph_api_endpoint: "https://graph.microsoft.com/v1.0"
    start_number: 1    # Starting number to check
    max_number: 100    # Maximum number to check
  tasks:
    - name: Get Azure access token
      uri:
        url: "https://login.microsoftonline.com/{{ tenant_id }}/oauth2/v2.0/token"
        method: POST
        body:
          client_id: "{{ client_id }}"
          client_secret: "{{ client_secret }}"
          scope: "https://graph.microsoft.com/.default"
          grant_type: "client_credentials"
        body_format: form-urlencoded
        return_content: yes
      register: azure_auth_response

    - name: Set Azure token
      set_fact:
        access_token: "{{ azure_auth_response.json.access_token }}"

    # Initialize variables
    - name: Initialize username variables
      set_fact:
        username_available: false
        available_nickname: ""
        
    # Generate a list of numbers to check
    - name: Generate sequence of numbers to check
      set_fact:
        check_numbers: "{{ range(start_number, max_number + 1) | list }}"
        
    # First task: Check each username until one is available
    - name: Check if username exists in Azure AD
      uri:
        url: "{{ graph_api_endpoint }}/users/{{ default_mail_nickname }}{{ item }}@{{ domain_name }}"
        method: GET
        headers:
          Authorization: "Bearer {{ access_token }}"
          Content-Type: "application/json"
        status_code: [200, 404]
        return_content: yes
      register: username_check
      ignore_errors: yes
      with_items: "{{ check_numbers }}"
      when: not username_available
      loop_control:
        label: "Checking {{ default_mail_nickname }}{{ item }}"
        
    # Process results after each check
    - name: Process check result
      set_fact:
        username_available: "{{ item.status is defined and item.status == 404 }}"
        available_nickname: "{{ default_mail_nickname }}{{ item.item }}"
      when: 
        - item.status is defined 
        - item.status == 404
      with_items: "{{ username_check.results | default([]) }}"
      loop_control:
        label: "Processing {{ default_mail_nickname }}{{ item.item | default('unknown') }}"
      
    - name: Debug - Final result
      debug:
        msg: >
          {% if username_available %}
          Found available username: {{ available_nickname }}@{{ domain_name }}
          {% else %}
          No available username found after checking {{ check_numbers | length }} options
          {% endif %}

    # Create user only if username is available
    - name: Create User in Azure AD with available username
      uri:
        url: "{{ graph_api_endpoint }}/users"
        method: POST
        headers:
          Authorization: "Bearer {{ access_token }}"
          Content-Type: "application/json"
        body:
          accountEnabled: true
          displayName: "{{ default_user_name }}"
          mailNickname: "{{ available_nickname }}"
          userPrincipalName: "{{ available_nickname }}@{{ domain_name }}"
          passwordProfile:
            forceChangePasswordNextSignIn: true
            password: "Default@1234"
        body_format: json
        status_code: [201]
      register: user_creation
      when: username_available
