- name: Fetch Pending ServiceNow Requests
  hosts: localhost
  gather_facts: no
  vars:
    servicenow_instance: "https://dev247928.service-now.com"
    servicenow_username: "admin"
    servicenow_password: "%ml4Vs9RXE/s"
    servicenow_table: "sc_request"
    tenant_id: "195e8969-c853-47b4-83d0-36e044d83923"
    client_id: "e2e46ae3-2dee-4eed-a074-ddffd760ab2b"
    client_secret: "PQZ8Q~XSmMsU4dbgk2KyWMHK1h8X7ciD~H.1_csi"
    default_user_email: "vidya@domain.com"
    default_user_name: "VidyaRa"
    default_mail_nickname: "vidya"
    domain_name: "amitomar63gmail.onmicrosoft.com"
    graph_api_endpoint: "https://graph.microsoft.com/v1.0"
    check_number: 3  # The specific number to check
  tasks:
    - name: Get Azure access token
      uri:
        url: "https://login.microsoftonline.com/{{ tenant_id }}/oauth2/v2.0/token"
        method: POST
        body:
          client_id: "{{ client_id }}"
          client_secret: "{{ client_secret }}"
          scope: "https://graph.microsoft.com/.default"
          grant_type: "client_credentials"
        body_format: form-urlencoded
        return_content: yes
      register: azure_auth_response

    - name: Set Azure token
      set_fact:
        access_token: "{{ azure_auth_response.json.access_token }}"

    # First, check the specified number
    - name: Check if the specified username exists in Azure AD
      uri:
        url: "{{ graph_api_endpoint }}/users/{{ default_mail_nickname }}{{ check_number }}@{{ domain_name }}"
        method: GET
        headers:
          Authorization: "Bearer {{ access_token }}"
          Content-Type: "application/json"
        status_code: [200, 404]
        return_content: yes
      register: username_check
      ignore_errors: yes
      
    - name: Debug check result
      debug:
        msg: "Checked {{ default_mail_nickname }}{{ check_number }} - Status: {{ username_check.status | default('error') }} (404 means available)"
      
    # Set the username based on the check
    - name: Set username based on check
      set_fact:
        available_nickname: "{{ default_mail_nickname }}{{ check_number }}"
        username_available: true
      when: username_check.status is defined and username_check.status == 404
      
    - name: Set username unavailable flag
      set_fact:
        username_available: false
      when: username_check.status is defined and username_check.status != 404

    - name: Debug - Selected username
      debug:
        msg: "Username {{ available_nickname | default('none') }}@{{ domain_name }} is {% if username_available | default(false) %}available{% else %}not available{% endif %}"

    # Create user only if username is available
    - name: Create User in Azure AD with available username
      uri:
        url: "{{ graph_api_endpoint }}/users"
        method: POST
        headers:
          Authorization: "Bearer {{ access_token }}"
          Content-Type: "application/json"
        body:
          accountEnabled: true
          displayName: "{{ default_user_name }}"
          mailNickname: "{{ available_nickname }}"
          userPrincipalName: "{{ available_nickname }}@{{ domain_name }}"
          passwordProfile:
            forceChangePasswordNextSignIn: true
            password: "Default@1234"
        body_format: json
        status_code: [201]
      register: user_creation
      when: username_available | default(false)
