---
- name: Fetch Pending ServiceNow Requests
  hosts: localhost
  gather_facts: no
  vars:
    servicenow_instance: "https://dev247928.service-now.com"
    servicenow_username: "{{ service_now_username }}"
    servicenow_password: "{{ service_now_password }}"
    tenant_id: "{{ azure_tenant_id }}"
    client_id: "{{ azure_client_id }}"
    client_secret: "{{ azure_client_secret }}"
    graph_api_endpoint: "https://graph.microsoft.com/v1.0"
    default_user_email: "vidya@domain.com"
    default_user_name: "VidyaRa"
    default_mail_nickname: "vidya"
    domain: "amitomar63gmail.onmicrosoft.com"
  tasks:
    - name: Get Azure access token
      uri:
        url: "https://login.microsoftonline.com/{{ tenant_id }}/oauth2/v2.0/token"
        method: POST
        body:
          client_id: "{{ client_id }}"
          client_secret: "{{ client_secret }}"
          scope: "https://graph.microsoft.com/.default"
          grant_type: "client_credentials"
        body_format: form-urlencoded
        return_content: yes
      register: azure_auth_response

    - name: Set Azure token
      set_fact:
        access_token: "{{ azure_auth_response.json.access_token }}"

    - name: Initialize variables for username attempt
      set_fact:
        current_nickname: "{{ default_mail_nickname }}"
        nickname_available: false
        attempt_count: 0
        max_attempts: 100  # Set a reasonable limit to avoid infinite loops

    - name: Find available username
      block:
        - name: Check if current username exists in Azure AD
          uri:
            url: "{{ graph_api_endpoint }}/users/{{ current_nickname }}@{{ domain }}"
            method: GET
            headers:
              Authorization: "Bearer {{ access_token }}"
              Content-Type: "application/json"
            status_code: [200, 404]
            return_content: yes
          register: user_check
          ignore_errors: yes

        - name: Set nickname available if user not found
          set_fact:
            nickname_available: true
          when: user_check.status == 404

        - name: Increment username when user exists
          block:
            - name: Increment attempt counter
              set_fact:
                attempt_count: "{{ attempt_count | int + 1 }}"

            - name: Generate new nickname
              set_fact:
                current_nickname: "{{ default_mail_nickname }}{{ attempt_count }}"

            - name: Debug - Show current nickname attempt
              debug:
                msg: "Attempting with nickname: {{ current_nickname }}"
          when: not nickname_available and attempt_count < max_attempts
      until: nickname_available or attempt_count >= max_attempts
      retries: "{{ max_attempts }}"
      delay: 1

    - name: Fail if no available username found after max attempts
      fail:
        msg: "Could not find an available username after {{ max_attempts }} attempts"
      when: not nickname_available

    - name: Debug - Show final nickname
      debug:
        msg: "Using nickname: {{ current_nickname }}"

    - name: Create User in Azure AD with available nickname
      uri:
        url: "{{ graph_api_endpoint }}/users"
        method: POST
        headers:
          Authorization: "Bearer {{ access_token }}"
          Content-Type: "application/json"
        body:
          accountEnabled: true
          displayName: "{{ default_user_name }}{% if attempt_count > 0 %}{{ attempt_count }}{% endif %}"
          mailNickname: "{{ current_nickname }}"
          userPrincipalName: "{{ current_nickname }}@{{ domain }}"
          passwordProfile:
            forceChangePasswordNextSignIn: true
            password: "Default@1234"
        body_format: json
        status_code: [201]
      register: user_creation
      when: nickname_available
