- name: Fetch Pending ServiceNow Requests
  hosts: localhost
  gather_facts: no
  vars:
    servicenow_instance: "https://dev247928.service-now.com"
    servicenow_username: "admin"
    servicenow_password: "%ml4Vs9RXE/s"
    servicenow_table: "sc_request"
    tenant_id: "195e8969-c853-47b4-83d0-36e044d83923"
    client_id: "e2e46ae3-2dee-4eed-a074-ddffd760ab2b"
    client_secret: "PQZ8Q~XSmMsU4dbgk2KyWMHK1h8X7ciD~H.1_csi"
    default_user_email: "vidya@domain.com"
    default_user_name: "VidyaRa"
    default_mail_nickname: "vidya"
    domain_name: "amitomar63gmail.onmicrosoft.com"
    graph_api_endpoint: "https://graph.microsoft.com/v1.0"
    start_number: 1    # Starting number to check
    max_number: 100    # Maximum number to check
  tasks:
    - name: Get Azure access token
      uri:
        url: "https://login.microsoftonline.com/{{ tenant_id }}/oauth2/v2.0/token"
        method: POST
        body:
          client_id: "{{ client_id }}"
          client_secret: "{{ client_secret }}"
          scope: "https://graph.microsoft.com/.default"
          grant_type: "client_credentials"
        body_format: form-urlencoded
        return_content: yes
      register: azure_auth_response

    - name: Set Azure token
      set_fact:
        access_token: "{{ azure_auth_response.json.access_token }}"
        current_number: "{{ start_number }}"
        username_available: false
        available_nickname: ""
        
    # Use a task within a meta loop to break when username found
    - name: Find first available username
      block:
        - name: Check if username exists in Azure AD
          uri:
            url: "{{ graph_api_endpoint }}/users/{{ default_mail_nickname }}{{ current_number }}@{{ domain_name }}"
            method: GET
            headers:
              Authorization: "Bearer {{ access_token }}"
              Content-Type: "application/json"
            status_code: [200, 404]
            return_content: yes
          register: username_check
          ignore_errors: yes
          
        - name: Debug current check
          debug:
            msg: "Checking {{ default_mail_nickname }}{{ current_number }} - Status: {{ username_check.status | default('error') }}"
          
        # If username is available, set flag and name
        - name: Set username if available
          set_fact:
            username_available: true
            available_nickname: "{{ default_mail_nickname }}{{ current_number }}"
          when: username_check.status is defined and username_check.status == 404
          
        # Break out of the loop if username found
        - name: Exit loop if username available
          meta: end_play
          when: username_available
          
        # Increment the counter for the next iteration
        - name: Increment counter for next check
          set_fact:
            current_number: "{{ current_number | int + 1 }}"
            
        # Exit if we've reached the maximum
        - name: Exit if maximum number reached
          meta: end_play
          when: current_number | int > max_number
          
      # Repeat the block until we hit a meta end_play
      until: current_number | int > max_number
      retries: "{{ max_number - start_number }}"
      delay: 1
      
    # This will only run if no username was found
    - name: Debug - No username found
      debug:
        msg: "No available username found after checking {{ max_number }} options"
      when: not username_available

    # Create user only if username is available - this runs in a separate play
  
- name: Create user if available username was found
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create User in Azure AD
      uri:
        url: "{{ graph_api_endpoint }}/users"
        method: POST
        headers:
          Authorization: "Bearer {{ access_token }}"
          Content-Type: "application/json"
        body:
          accountEnabled: true
          displayName: "{{ default_user_name }}"
          mailNickname: "{{ available_nickname }}"
          userPrincipalName: "{{ available_nickname }}@{{ domain_name }}"
          passwordProfile:
            forceChangePasswordNextSignIn: true
            password: "Default@1234"
        body_format: json
        status_code: [201]
      register: user_creation
      when: username_available
      
    - name: Debug - User creation result
      debug:
        msg: "Successfully created user: {{ available_nickname }}@{{ domain_name }}"
      when: username_available and user_creation.status == 201
