- name: Fetch Pending ServiceNow Requests
  hosts: localhost
  gather_facts: no
  vars:
    servicenow_instance: "https://dev247928.service-now.com"
    servicenow_username: "admin"
    servicenow_password: "%ml4Vs9RXE/s"
    servicenow_table: "sc_request"
    tenant_id: "195e8969-c853-47b4-83d0-36e044d83923"
    client_id: "e2e46ae3-2dee-4eed-a074-ddffd760ab2b"
    client_secret: "PQZ8Q~XSmMsU4dbgk2KyWMHK1h8X7ciD~H.1_csi"
    default_user_email: "vidya@domain.com"
    default_user_name: "VidyaRa"
    default_mail_nickname: "vidya"
    domain_name: "amitomar63gmail.onmicrosoft.com"
    graph_api_endpoint: "https://graph.microsoft.com/v1.0"
    user_number:100

  tasks:
    - name: Get Azure access token
      uri:
        url: "https://login.microsoftonline.com/{{ tenant_id }}/oauth2/v2.0/token"
        method: POST
        body:
          client_id: "{{ client_id }}"
          client_secret: "{{ client_secret }}"
          scope: "https://graph.microsoft.com/.default"
          grant_type: "client_credentials"
        body_format: form-urlencoded
        return_content: yes
      register: azure_auth_response

    - name: Set Azure token
      set_fact:
        access_token: "{{ azure_auth_response.json.access_token }}"

    - name: Check if original username exists in Azure AD
      uri:
        url: "{{ graph_api_endpoint }}/users/{{ default_mail_nickname }}@{{ domain_name }}"
        method: GET
        headers:
          Authorization: "Bearer {{ access_token }}"
          Content-Type: "application/json"
        status_code: [200, 404]
        return_content: yes
      register: user_check
      ignore_errors: yes

    - name: Debug user_check response
      debug:
        var: user_check

    - name: Set initial username if user does not exist
      set_fact:
        current_nickname: "{{ default_mail_nickname }}"
      when: user_check.status is defined and user_check.status == 404

    - name: Find available username if original exists
      set_fact:
        current_nickname: "{{ default_mail_nickname }}{{ item }}"
      with_sequence: start=1 end={{ user_number }}
      when: user_check.status is defined and user_check.status == 200

    - name: Verify if selected username is available
      uri:
        url: "{{ graph_api_endpoint }}/users/{{ current_nickname }}@{{ domain_name }}"
        method: GET
        headers:
          Authorization: "Bearer {{ access_token }}"
          Content-Type: "application/json"
        status_code: [200, 404]
        return_content: yes
      register: incremented_user_check
      ignore_errors: yes
      until: incremented_user_check.status == 404
      retries: 1
      delay: 1

    - name: Debug - Selected username
      debug:
        msg: "Selected username: {{ current_nickname }}@{{ domain_name }}"

    - name: Create User in Azure AD with available username
      uri:
        url: "{{ graph_api_endpoint }}/users"
        method: POST
        headers:
          Authorization: "Bearer {{ access_token }}"
          Content-Type: "application/json"
        body:
          accountEnabled: true
          displayName: "{{ default_user_name }}"
          mailNickname: "{{ current_nickname }}"
          userPrincipalName: "{{ current_nickname }}@{{ domain_name }}"
          passwordProfile:
            forceChangePasswordNextSignIn: true
            password: "Default@1234"
        body_format: json
        status_code: [201]
      register: user_creation
