---
- name: Fetch Pending ServiceNow Requests
  hosts: localhost
  gather_facts: no
  vars:
    servicenow_instance: "https://dev247928.service-now.com"
    servicenow_username: "{{ service_now_username }}"
    servicenow_password: "{{ service_now_password }}"
    tenant_id: "{{ azure_tenant_id }}"
    client_id: "{{ azure_client_id }}"
    client_secret: "{{ azure_client_secret }}"
    graph_api_endpoint: "https://graph.microsoft.com/v1.0"
    default_user_email: "{{ awx_webhook_payload.user_email }}"
    default_user_name: "{{ awx_webhook_payload.user_name}}"
    default_mail_nickname: "{{ awx_webhook_payload.nickname}}"
    request_sys_id: "a9dd9bf283446210d081f696feaad3e6"
    ritm_sys_id: "21dd9bf283446210d081f696feaad3e7"
  tasks:
    - name: Set ServiceNow auth header
      set_fact:
        snow_auth: "{{ servicenow_username }}:{{ servicenow_password }}"
      
    - name: Update ServiceNow Request Item (RITM) status
      uri:
        url: "{{ servicenow_instance }}/api/now/table/sc_req_item/{{ ritm_sys_id }}"
        method: PATCH
        user: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        headers:
          Content-Type: "application/json"
          Accept: "application/json"
        body_format: json
        body:
          stage: "completed"
          state: "3"  # 3 corresponds to "Closed Complete" in ServiceNow
        status_code: [200, 201]
        return_content: yes
      register: ritm_update_result
      when: user_creation is defined and user_creation.skipped is not defined
      
    - name: Debug RITM update result
      debug:
        var: ritm_update_result
      when: ritm_update_result is defined
        
    - name: Update ServiceNow Request status
      uri:
        url: "{{ servicenow_instance }}/api/now/table/sc_request/{{ request_sys_id }}"
        method: PATCH
        user: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        headers:
          Content-Type: "application/json"
          Accept: "application/json"
        body_format: json
        body:
          request_state: "closed_complete"  # Closed Complete state
        status_code: [200, 201]
        return_content: yes
      register: request_update_result
      when: user_creation is defined and user_creation.skipped is not defined
      
    - name: Debug Request update result
      debug:
        var: request_update_result
      when: request_update_result is defined
      
    - name: Report success
      debug:
        msg: "User creation and ServiceNow update workflow completed successfully"
      when: user_creation is defined and user_creation.skipped is not defined and ritm_update_result is defined and request_update_result is defined
