---
- name: Fetch Pending ServiceNow Requests
  hosts: localhost
  gather_facts: no
  vars:
    servicenow_instance: "https://dev247928.service-now.com"
    servicenow_username: "admin"
    servicenow_password: "%ml4Vs9RXE/s"
    tenant_id: "195e8969-c853-47b4-83d0-36e044d83923"
    client_id: "e2e46ae3-2dee-4eed-a074-ddffd760ab2b"
    client_secret: "PQZ8Q~XSmMsU4dbgk2KyWMHK1h8X7ciD~H.1_csi"
    graph_api_endpoint: "https://graph.microsoft.com/v1.0"
    default_user_email: "vidyar@gmail.com"
    default_user_name: "vidyar"
    default_mail_nickname: "vidyar"
    requested_sys_id: "223a928b83c0a210d081f696feaad3f7"
  tasks:
    - name: Get Azure access token
      uri:
        url: "https://login.microsoftonline.com/{{ tenant_id }}/oauth2/v2.0/token"
        method: POST
        body:
          client_id: "{{ client_id }}"
          client_secret: "{{ client_secret }}"
          scope: "https://graph.microsoft.com/.default"
          grant_type: "client_credentials"
        body_format: form-urlencoded
        return_content: yes
      register: azure_auth_response
    
    - name: Set Azure token
      set_fact:
        access_token: "{{ azure_auth_response.json.access_token }}"
    
    - name: Check if user exists in Azure AD
      uri:
        url: "{{ graph_api_endpoint }}/users/{{ default_mail_nickname }}@amitomar63gmail.onmicrosoft.com"
        method: GET
        headers:
          Authorization: "Bearer {{ access_token }}"
          Content-Type: "application/json"
        status_code: [200, 404]
        return_content: yes
      register: user_check
      ignore_errors: yes
    
    - name: Debug - Show User Check Results
      debug:
        var: user_check
    
    - name: Create User in Azure AD if Not Exists
      uri:
        url: "{{ graph_api_endpoint }}/users"
        method: POST
        headers:
          Authorization: "Bearer {{ access_token }}"
          Content-Type: "application/json"
        body:
          accountEnabled: true
          displayName: "{{ default_user_name }}"
          mailNickname: "{{ default_mail_nickname }}"
          userPrincipalName: "{{ default_mail_nickname }}@amitomar63gmail.onmicrosoft.com"
          passwordProfile:
            forceChangePasswordNextSignIn: true
            password: "Default@1234"
        body_format: json
        status_code: [201]
      register: user_creation
      when: user_check.status == 404
    
    - name: Update ServiceNow Ticket with Correlation ID
      uri:
        url: "{{ servicenow_instance }}/api/now/table/incident/{{ requested_sys_id }}"
        method: PATCH
        headers:
          Accept: "application/json"
          Content-Type: "application/json"
        auth:
          - "{{ servicenow_username }}"
          - "{{ servicenow_password }}"
        body:
          correlation_id: "true"
        body_format: json
        status_code: [200, 204]
    
    # New tasks to close the ServiceNow request after successful user creation
    - name: Get Request Item information
      uri:
        url: "{{ servicenow_instance }}/api/now/table/sc_req_item?sysparm_query=request.sys_id={{ requested_sys_id }}"
        method: GET
        headers:
          Accept: "application/json"
        auth:
          - "{{ servicenow_username }}"
          - "{{ servicenow_password }}"
        return_content: yes
      register: req_item_info
      when: user_creation is defined and user_creation.status == 201
    
    - name: Debug - Request Item Information
      debug:
        var: req_item_info
      when: user_creation is defined and user_creation.status == 201
    
    - name: Close Request Item in ServiceNow
      uri:
        url: "{{ servicenow_instance }}/api/now/table/sc_req_item/{{ item.sys_id }}"
        method: PATCH
        headers:
          Accept: "application/json"
          Content-Type: "application/json"
        auth:
          - "{{ servicenow_username }}"
          - "{{ servicenow_password }}"
        body:
          state: "3"  # 3 = Closed Complete
          close_notes: "User successfully created in Azure AD with UPN: {{ default_mail_nickname }}@amitomar63gmail.onmicrosoft.com"
        body_format: json
        status_code: [200, 204]
      with_items: "{{ req_item_info.json.result }}"
      when: 
        - user_creation is defined 
        - user_creation.status == 201
        - req_item_info.json.result | length > 0
    
    - name: Close the Request in ServiceNow
      uri:
        url: "{{ servicenow_instance }}/api/now/table/sc_request/{{ requested_sys_id }}"
        method: PATCH
        headers:
          Accept: "application/json"
          Content-Type: "application/json"
        auth:
          - "{{ servicenow_username }}"
          - "{{ servicenow_password }}"
        body:
          state: "3"  # 3 = Closed Complete
          close_notes: "User successfully created in Azure AD. Request completed."
        body_format: json
        status_code: [200, 204]
      when: user_creation is defined and user_creation.status == 201
    
    - name: Send notification email about completion
      uri:
        url: "{{ servicenow_instance }}/api/now/table/sys_email"
        method: POST
        headers:
          Accept: "application/json"
          Content-Type: "application/json"
        auth:
          - "{{ servicenow_username }}"
          - "{{ servicenow_password }}"
        body:
          type: "send-now"
          recipients: "{{ default_user_email }}"
          subject: "Azure AD User Creation Complete"
          body: |
            Hello {{ default_user_name }},
            
            Your Azure AD user has been successfully created with the following details:
            - Username: {{ default_mail_nickname }}@amitomar63gmail.onmicrosoft.com
            - Initial Password: Default@1234
            
            You will be required to change your password on first login.
            
            Thank you,
            IT Service Desk
        body_format: json
        status_code: [201]
      when: user_creation is defined and user_creation.status == 201
