---
# mysql_connection.yml - Ansible playbook to connect to a MySQL server
- name: Connect to MySQL Server
  hosts: mysql_servers  # Define this group in your inventory
  become: true  # Use sudo privileges
  gather_facts: true

  vars:
    mysql_host: "{{ mysql_server_host | default('localhost') }}"
    mysql_port: "{{ mysql_server_port | default('3306') }}"
    mysql_user: "{{ mysql_server_user | default('root') }}"
    mysql_password: "{{ mysql_server_password | default('') }}"
    mysql_db: "{{ mysql_server_db | default('mysql') }}"
    
  tasks:
    - name: Install MySQL client
      package:
        name: "{{ item }}"
        state: present
      loop:
        - mysql-client  # Debian/Ubuntu
        - python3-pymysql  # Required for Ansible MySQL modules
      failed_when: false  # Continue if a package isn't available on this distro
      
    - name: Install MySQL client (RedHat/CentOS)
      package:
        name: "{{ item }}"
        state: present
      loop:
        - mysql  # RedHat/CentOS
        - python3-PyMySQL  # RedHat/CentOS
      when: ansible_facts['os_family'] == "RedHat"
      failed_when: false
    
    - name: Create MySQL config file with connection details
      template:
        src: my.cnf.j2
        dest: ~/.my.cnf
        mode: '0600'  # Secure permissions for credential file
      become: false  # Create in user's home directory
      
    - name: Test MySQL connection
      community.mysql.mysql_info:
        login_host: "{{ mysql_host }}"
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
        login_port: "{{ mysql_port }}"
      register: mysql_status
      become: false
      ignore_errors: true
      
    - name: Display MySQL connection status
      debug:
        msg: "MySQL connection successful. Version: {{ mysql_status.version.full }}"
      when: mysql_status is succeeded
        
    - name: Display connection failure message
      debug:
        msg: "Failed to connect to MySQL. Please check credentials and network access."
      when: mysql_status is failed
