---
- name: MySQL Monitoring Playbook
  hosts: localhost
  gather_facts: no
  vars:
    mysql_host: "20.55.88.203"
    mysql_database: "information_schema"
    mysql_username: "mysqlauto"
    mysql_password: "mysqlAutomation"
    mysql_port: "3306"

  tasks:
    - name: Check MySQL connection
      shell: >
        mysql --host={{ mysql_host }} --user={{ mysql_username }} 
        --password={{ mysql_password }} -e 'SELECT 1;'
      register: mysql_conn_result
      changed_when: false
      ignore_errors: yes

    - name: Print connection status
      debug:
        msg: "[✅] Connected to MySQL Server successfully"
      when: mysql_conn_result is succeeded

    - name: Print connection error
      debug:
        msg: "[❌] MySQL Connection Error: {{ mysql_conn_result.stderr }}"
      when: mysql_conn_result is failed

    - block:
        - name: Check database space utilization
          shell: >
            mysql --host={{ mysql_host }} --user={{ mysql_username }} 
            --password={{ mysql_password }} -e "
            SELECT table_schema AS DatabaseName,
                   ROUND(SUM(data_length + index_length) / 1024 / 1024, 2) AS TotalSizeMB
            FROM information_schema.tables
            GROUP BY table_schema;"
          register: db_space_result
          changed_when: false

        - name: Display database space utilization
          debug:
            msg: "📊 Database Space Utilization: {{ db_space_result.stdout }}"

        - name: Check for deadlocks
          shell: >
            mysql --host={{ mysql_host }} --user={{ mysql_username }} 
            --password={{ mysql_password }} -e "SHOW ENGINE INNODB STATUS\G" | 
            grep -A 10 "LATEST DETECTED DEADLOCK"
          register: deadlock_result
          changed_when: false
          ignore_errors: yes

        - name: Display deadlock information
          debug:
            msg: >
              🚨 Deadlocks: {{ 
                "Deadlock detected:\n" + deadlock_result.stdout if deadlock_result.stdout_lines|length > 0 
                else "No deadlocks detected" 
              }}

        - name: Check MySQL event scheduler activities
          shell: >
            mysql --host={{ mysql_host }} --user={{ mysql_username }} 
            --password={{ mysql_password }} --database={{ mysql_database }} -e "
            SELECT event_name, status
            FROM information_schema.events
            WHERE status = 'ENABLED';"
          register: events_result
          changed_when: false
          ignore_errors: yes

        - name: Display event scheduler activities
          debug:
            msg: "🛠 MySQL Event Activities:\n{{ events_result.stdout }}"
          when: events_result.stdout_lines|length > 1

        - name: Display no active events message
          debug:
            msg: "🛠 MySQL Event Activities: No active events found."
          when: events_result.stdout_lines|length <= 1

        - name: Check MySQL version
          shell: >
            mysql --host={{ mysql_host }} --user={{ mysql_username }} 
            --password={{ mysql_password }} -e 'SELECT VERSION();'
          register: mysql_version
          changed_when: false

        - name: Display MySQL version
          debug:
            msg: "[ℹ️] MySQL Version: {{ mysql_version.stdout }}"

        - name: Check MySQL health status (active connections)
          shell: >
            mysql --host={{ mysql_host }} --user={{ mysql_username }} 
            --password={{ mysql_password }} -e "
            SHOW STATUS LIKE 'Threads_connected';"
          register: health_result
          changed_when: false

        - name: Display MySQL health information
          debug:
            msg: "🩺 Database Health Check:\n{{ health_result.stdout }}"

      when: mysql_conn_result is succeeded
