---
- name: Check MySQL Connection in AWX (Using Ansible modules)
  hosts: localhost
  gather_facts: no
  vars:
    mysql_host: "10.112.0.11"
    mysql_user: "root"
    mysql_password: "mysqlAutomation"
    mysql_port: 3306
  tasks:
    - name: Install required Python modules
      pip:
        name:
          - pymysql
          - mysqlclient
        state: present
      ignore_errors: yes
      
    - name: Test MySQL Connection
      community.mysql.mysql_info:
        login_host: "{{ mysql_host }}"
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
        login_port: "{{ mysql_port }}"
      register: mysql_connection
      ignore_errors: yes
      
    - name: Display Connection Result
      debug:
        msg: |
          {% if mysql_connection is success %}
          ✅ MySQL Connection Successful!
          MySQL Version: {{ mysql_connection.version.major }}.{{ mysql_connection.version.minor }}.{{ mysql_connection.version.release }}
          {% else %}
          ❌ MySQL Connection Failed!
          Error: {{ mysql_connection.msg }}
          {% endif %}
          
    - name: Set Connection Status Fact
      set_fact:
        mysql_connection_status: "{{ mysql_connection is success }}"
        
    - name: Fail if Connection Unsuccessful
      fail:
        msg: "Failed to connect to MySQL server at {{ mysql_host }}:{{ mysql_port }}"
      when: not mysql_connection is success
