---
- name: Check MySQL Connection
  hosts: localhost
  gather_facts: no
  vars:
    mysql_host: "10.112.0.11"
    mysql_user: "mysqlauto"
    mysql_password: "mysqlAutomation"
    mysql_port: 3306

  tasks:
    - name: Test MySQL Connection
      shell: |
        mysql -h{{ mysql_host }} -P{{ mysql_port }} -u{{ mysql_user }} -p{{ mysql_password }} -e "SELECT 1;"
      register: mysql_connection
      ignore_errors: yes
      
    - name: Display Connection Result
      debug:
        msg: |
          {% if mysql_connection.rc == 0 %}
          ✅ MySQL Connection Successful!
          {% else %}
          ❌ MySQL Connection Failed!
          Error: {{ mysql_connection.stderr }}
          {% endif %}
          
    - name: Set Connection Status Fact
      set_fact:
        mysql_connection_status: "{{ mysql_connection.rc == 0 }}"
        
    - name: Fail if Connection Unsuccessful
      fail:
        msg: "Failed to connect to MySQL server at {{ mysql_host }}:{{ mysql_port }}"
      when: not mysql_connection_status
