---
- name: Check MySQL Client in AWX
  hosts: localhost
  gather_facts: no
  
  tasks:
    - name: Check if MySQL client is installed
      command: which mysql
      register: mysql_client_check
      ignore_errors: yes
      changed_when: false

    - name: Show MySQL client status
      debug:
        msg: "MySQL client {{ 'is available' if mysql_client_check.rc == 0 else 'is NOT available' }}"
