---
- name: Connect to MySQL Server
  hosts: localhost
  become: yes
  vars:
    mysql_root_password: "mysqlAutomation"
    mysql_user: "mysqlauto"
    mysql_password: "mysqlAutomation"
    mysql_host: "20.55.88.203"
  
  tasks:
    - name: Install MySQL and dependencies
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - mysql-server
        - python3-mysqldb
        - python3-pip

    - name: Ensure MySQL service is running
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Create a MySQL user
      community.mysql.mysql_user:
        name: "{{ mysql_user }}"
        password: "{{ mysql_password }}"
        priv: "*.*:ALL"
        host: "%"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Create a MySQL database
      community.mysql.mysql_db:
        name: test_db
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Test MySQL Connection
      command: mysql -u {{ mysql_user }} -p{{ mysql_password }} -e "SHOW DATABASES;"
      register: mysql_output

    - name: Display MySQL Databases
      debug:
        msg: "{{ mysql_output.stdout }}"
