---
- name: Check MySQL Connection in AWX (Python only)
  hosts: localhost
  gather_facts: no
  vars:
    mysql_host: "10.112.0.11"
    mysql_user: "root"
    mysql_password: "mysqlAutomation"
    mysql_port: 3306

  tasks:
    - name: Install pymysql
      pip:
        name: pymysql
        state: present
      register: pymysql_install
      ignore_errors: yes

    - name: Test MySQL Connection with Python
      shell: |
        python3 -c "
        import sys
        try:
            import pymysql
            try:
                conn = pymysql.connect(
                    host='{{ mysql_host }}',
                    user='{{ mysql_user }}',
                    password='{{ mysql_password }}',
                    port={{ mysql_port }},
                    connect_timeout=5
                )
                print('Connection successful')
                conn.close()
                sys.exit(0)
            except Exception as e:
                print(f'MySQL Connection failed: {e}')
                sys.exit(1)
        except ImportError:
            print('PyMySQL module not available')
            sys.exit(2)
        "
      register: mysql_py_connection
      ignore_errors: yes
      
    - name: Display Connection Result
      debug:
        msg: |
          {% if mysql_py_connection.rc == 0 %}
          ✅ MySQL Connection Successful!
          {% elif mysql_py_connection.rc == 2 %}
          ⚠️ Could not test connection: PyMySQL module not available
          {% else %}
          ❌ MySQL Connection Failed!
          Error: {{ mysql_py_connection.stdout }}
          {% endif %}
          
    - name: Set Connection Status Fact
      set_fact:
        mysql_connection_status: "{{ mysql_py_connection.rc == 0 }}"
        
    - name: Fail if Connection Unsuccessful
      fail:
        msg: "Failed to connect to MySQL server at {{ mysql_host }}:{{ mysql_port }}"
      when: mysql_py_connection.rc == 1
