---
- hosts: 20.55.88.203
  become: true
  gather_facts: false
  tasks:
    - name: Connect to MySQL server
      mysql_db:
        host: "mysqlAutomation"
        port: "3306"
        user: "mysqlauto"
        password: "mysqlAutomation"
      register: mysql_result

    - name: Print the result
      debug:
        msg: "{{ mysql_result }}"
