---
- name: Check MySQL Server Health
  hosts: localhost
  gather_facts: no
  vars:
    mysql_host: "10.112.0.11"
    mysql_user: "mysqlauto" 
    mysql_password: "mysqlAutomation"
    mysql_port: 3306
