---
- name: SQL Server Health Check and Maintenance
  hosts: 10.112.0.10
  gather_facts: no
  vars:
    sql_instance: "10.112.0.10"
    sql_user: "{{ sql_user }}"
    sql_password: "{{ sql_password }}"

  tasks:
    - name: Get Disk Space Utilization
      win_shell: |
        try {
          $disks = Get-WmiObject Win32_LogicalDisk | Select-Object DeviceID, VolumeName, Size, FreeSpace | ConvertTo-Json -Compress -Depth 2
          if (-not $disks) { Write-Output '[]' } else { Write-Output $disks }
        } catch {
          Write-Output '[{"Error": "Failed to retrieve disk info"}]'
        }
      register: disk_space
      ignore_errors: yes

    - name: Get Database Space Utilization
      win_shell: |
        try {
          $query = "SELECT DB_NAME(database_id) AS DatabaseName, SUM(size * 8) / 1024 AS SizeMB FROM sys.master_files GROUP BY database_id;"
          $result = Invoke-Sqlcmd -Query "$query" -ServerInstance "{{ sql_instance }}" -Username "{{ sql_user }}" -Password "{{ sql_password }}" -TrustServerCertificate | ConvertTo-Json -Compress -Depth 3
          if (-not $result) { Write-Output '[]' } else { Write-Output $result }
        } catch {
          Write-Output '[{"Error": "Failed to retrieve database space info"}]'
        }
      register: db_space
      ignore_errors: yes

    - name: Get Database Health
      win_shell: |
        try {
          $query = "SELECT db.name AS DatabaseName, db.state_desc AS Status, (SELECT COUNT(*) FROM sys.dm_exec_requests r WHERE r.database_id = db.database_id) AS ActiveRequests, (SELECT COUNT(*) FROM sys.dm_exec_sessions s WHERE s.is_user_process = 1 AND s.database_id = db.database_id) AS ActiveUserConnections, (SELECT COUNT(*) FROM sys.dm_os_waiting_tasks w JOIN sys.dm_exec_sessions s ON w.session_id = s.session_id WHERE s.database_id = db.database_id) AS PendingRequests, (SELECT COUNT(*) FROM sys.dm_os_performance_counters WHERE counter_name = 'Processor Queue Length') AS CPUQueueLength FROM sys.databases db;"
          $result = Invoke-Sqlcmd -Query "$query" -ServerInstance "{{ sql_instance }}" -Username "{{ sql_user }}" -Password "{{ sql_password }}" -TrustServerCertificate | ConvertTo-Json -Compress -Depth 3
          if (-not $result) { Write-Output '[]' } else { Write-Output $result }
        } catch {
          Write-Output '[{"Error": "' + $_.Exception.Message + '"}]'
        }
      register: db_health
      ignore_errors: yes

    - name: Check for Deadlocks
      win_shell: |
        try {
          $query = "SELECT COUNT(*) AS Deadlocks FROM sys.dm_tran_locks WHERE request_status = 'WAIT';"
          $result = Invoke-Sqlcmd -Query "$query" -ServerInstance "{{ sql_instance }}" -Username "{{ sql_user }}" -Password "{{ sql_password }}" -TrustServerCertificate | ConvertTo-Json -Compress
          if (-not $result) { Write-Output '[{"Deadlocks": 0}]' } else { Write-Output $result }
        } catch {
          Write-Output '[{"Deadlocks": "Error"}]'
        }
      register: deadlocks
      ignore_errors: yes

    - name: Get SQL Agent Job Activities
      win_shell: |
        try {
          $query = "SELECT j.job_id, j.name, j.enabled, MAX(h.run_status) AS last_run_status FROM msdb.dbo.sysjobs j LEFT JOIN msdb.dbo.sysjobhistory h ON j.job_id = h.job_id WHERE h.step_id = 0 GROUP BY j.job_id, j.name, j.enabled;"
          $result = Invoke-Sqlcmd -Query "$query" -ServerInstance "{{ sql_instance }}" -Username "{{ sql_user }}" -Password "{{ sql_password }}" -TrustServerCertificate | ConvertTo-Json -Compress -Depth 3
          if (-not $result) { Write-Output '[]' } else { Write-Output $result }
        } catch {
          Write-Output '[{"Error": "' + $_.Exception.Message + '"}]'
        }
      register: job_activities
      ignore_errors: yes

    - name: Check SQL Server Error Log for Issues
      win_shell: |
        try {
          $query = "SELECT TOP 10 logdate, processinfo, text FROM sys.fn_get_audit_file('C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\Log\*.sqlaudit', DEFAULT, DEFAULT) WHERE text LIKE '%error%' OR text LIKE '%failed%' OR text LIKE '%severity%' ORDER BY logdate DESC;"
          $result = Invoke-Sqlcmd -Query "$query" -ServerInstance "{{ sql_instance }}" -Username "{{ sql_user }}" -Password "{{ sql_password }}" -TrustServerCertificate | ConvertTo-Json -Compress -Depth 3
          if (-not $result) { Write-Output '[]' } else { Write-Output $result }
        } catch {
          Write-Output '[{"Error": "' + $_.Exception.Message + '"}]'
        }
      register: sql_errors
      ignore_errors: yes

    - name: Convert Outputs to JSON
      set_fact:
        db_space_fact: "{{ db_space.stdout | default('[]') | from_json }}"
        db_health_fact: "{{ db_health.stdout | default('[]') | from_json }}"
        deadlocks_fact: "{{ deadlocks.stdout | default('[]') | from_json }}"
        job_activities_fact: "{{ job_activities.stdout | default('[]') | from_json }}"
        disk_space_fact: "{{ disk_space.stdout | default('[]') | from_json }}"
        sql_errors_fact: "{{ sql_errors.stdout | default('[]') | from_json }}"
        
    - name: Check for Offline Databases
      set_fact:
        has_offline_db: false
        offline_db_names: []
      no_log: true

    - name: Mark Offline Databases
      set_fact:
        has_offline_db: true
        offline_db_names: "{{ offline_db_names + [item.DatabaseName] }}"
      when: item.Status == "OFFLINE"
      with_items: "{{ db_health_fact }}"
      no_log: true

    - name: Display SQL Server Issues and Troubleshooting Suggestions
      debug:
        msg: |
          #########################################################################
          #                SQL SERVER HEALTH CHECK SUMMARY REPORT                 #
          #########################################################################

          ⚠️ **CRITICAL SQL SERVER ISSUES:**
          {% if sql_errors_fact is defined and sql_errors_fact | length > 0 %}
            {% for error in sql_errors_fact %}
              - **Timestamp:** {{ error.logdate | default("N/A") }}
              - **Process:** {{ error.processinfo | default("N/A") }}
              - **Error Message:** {{ error.text | default("N/A") }}
              **🔧 Suggested Troubleshooting Steps:**
              {% if 'login failed' in error.text | lower %}
                - Check SQL login credentials.
                - Verify if the login exists and is enabled (`SELECT * FROM sys.sql_logins`).
                - Ensure correct authentication mode is set (`SELECT SERVERPROPERTY('IsIntegratedSecurityOnly')`).
              {% elif 'deadlock' in error.text | lower %}
                - Identify deadlock victims (`SELECT * FROM sys.dm_tran_locks`).
                - Review long-running transactions.
                - Optimize indexing and query performance.
              {% elif 'severity 17' in error.text | lower %}
                - Indicates insufficient resources. Check available memory and disk space.
                - Review running processes with `sys.dm_exec_requests`.
              {% elif 'severity 20' in error.text | lower %}
                - Fatal error detected. Check error log for more details.
                - Restart SQL Server if necessary.
              {% else %}
                - Review the error message and check SQL documentation for resolution.
              {% endif %}
            {% endfor %}
          {% endif %}
          
          {% if has_offline_db %}
            {% for db in db_health_fact %}
              {% if db.Status == "OFFLINE" %}
              🚨 **CRITICAL: Database {{ db.DatabaseName }} is OFFLINE!**
              - **Possible reasons:**
                - Manually taken offline
                - Storage or corruption issues
                - SQL Server restart
              - **Suggested Fix:**
                - `ALTER DATABASE {{ db.DatabaseName }} SET ONLINE;`
                - Check storage space and error logs
              {% endif %}
            {% endfor %}
          {% elif sql_errors_fact | length == 0 %}
            ✅ No critical errors found in the SQL Server logs.
          {% endif %}

          #########################################################################
          
          📊 **DISK SPACE UTILIZATION:**
          {% if disk_space_fact is defined and disk_space_fact | length > 0 %}
            {% for disk in disk_space_fact %}
              - Drive: {{ disk.DeviceID }}
              {% if disk.VolumeName %}  - Name: {{ disk.VolumeName }}{% endif %}
              {% if disk.Size %}  - Total Size: {{ (disk.Size / 1073741824) | round(2) }} GB{% endif %}
              {% if disk.FreeSpace %}  - Free Space: {{ (disk.FreeSpace / 1073741824) | round(2) }} GB ({{ ((disk.FreeSpace / disk.Size) * 100) | round(2) }}%){% endif %}
              {% if (disk.FreeSpace / disk.Size) < 0.1 %}  - ⚠️ **LOW DISK SPACE WARNING!**{% endif %}
            {% endfor %}
          {% else %}
            ❌ No disk space information available.
          {% endif %}
          
          #########################################################################
          
          💾 **DATABASE SPACE UTILIZATION:**
          {% if db_space_fact is defined and db_space_fact | length > 0 %}
            {% for db in db_space_fact %}
              - Database: {{ db.DatabaseName }}
                - Size: {{ db.SizeMB | round(2) }} MB
            {% endfor %}
          {% else %}
            ❌ No database space information available.
          {% endif %}
          
          #########################################################################
          
          🩺 **DATABASE HEALTH:**
          {% if db_health_fact is defined and db_health_fact | length > 0 %}
            {% for db in db_health_fact %}
              - Database: {{ db.DatabaseName }}
                - Status: {{ db.Status }}
                - Active Requests: {{ db.ActiveRequests }}
                - Active User Connections: {{ db.ActiveUserConnections }}
                - Pending Requests: {{ db.PendingRequests }}
              {% if db.Status == "OFFLINE" %}
                🚨 **ALERT: Database {{ db.DatabaseName }} is OFFLINE!**
              {% endif %}
              {% if db.ActiveRequests > 10 %}
                ⚠️ **HIGH ACTIVITY: {{ db.ActiveRequests }} active requests in {{ db.DatabaseName }}**
              {% endif %}
            {% endfor %}
          {% else %}
            ❌ No database health information available.
          {% endif %}
          
          #########################################################################
          
          🔒 **DEADLOCKS CHECK:**
          {% if deadlocks_fact is defined %}
            {% if deadlocks_fact[0].Deadlocks is defined and deadlocks_fact[0].Deadlocks != "Error" %}
              {% if deadlocks_fact[0].Deadlocks > 0 %}
                🚨 **ALERT: {{ deadlocks_fact[0].Deadlocks }} deadlocks detected!**
                - Run this query to identify affected resources:
                  `SELECT * FROM sys.dm_tran_locks WHERE request_status = 'WAIT';`
              {% else %}
                ✅ No deadlocks detected.
              {% endif %}
            {% else %}
              ❌ Error retrieving deadlock information.
            {% endif %}
          {% else %}
            ❌ No deadlock information available.
          {% endif %}
          
          #########################################################################
          
          📋 **SQL AGENT JOB ACTIVITIES:**
          {% if job_activities_fact is defined and job_activities_fact | length > 0 %}
            {% for job in job_activities_fact %}
              - Job Name: {{ job.name }}
                - Enabled: {{ 'Yes' if job.enabled == 1 else 'No' }}
                - Last Run Status: {% if job.last_run_status == 1 %}✅ Success{% elif job.last_run_status == 0 %}❌ Failed{% elif job.last_run_status == 2 %}⚠️ Retry{% elif job.last_run_status == 3 %}⏹️ Canceled{% else %}⚠️ Unknown ({{ job.last_run_status }}){% endif %}
            {% endfor %}
          {% else %}
            ❌ No SQL Agent job information available.
          {% endif %}
