---
- name: Check MySQL Server Health on Linux
  hosts: localhost
  gather_facts: no
  vars:
    mysql_host: "20.55.88.203"
    mysql_user: "mysqlauto"
    mysql_password: "mysqlAutomation"
    mysql_db: "information_schema"

  tasks:
    - name: Get Database Space Utilization
      shell: |
        mysql -h {{ mysql_host }} -u {{ mysql_user }} -p{{ mysql_password }} -e "
        SELECT table_schema AS DatabaseName, 
        ROUND(SUM(data_length + index_length) / 1024 / 1024, 2) AS SizeMB 
        FROM information_schema.TABLES 
        GROUP BY table_schema;
        "
      register: db_space
      ignore_errors: yes

    - name: Get Database Health
      shell: |
        mysql -h {{ mysql_host }} -u {{ mysql_user }} -p{{ mysql_password }} -e "
        SELECT SCHEMA_NAME AS DatabaseName, 
        'N/A' AS Status, 
        (SELECT COUNT(*) FROM information_schema.PROCESSLIST) AS ActiveRequests, 
        (SELECT COUNT(*) FROM information_schema.PROCESSLIST WHERE USER IS NOT NULL) AS ActiveUserConnections, 
        (SELECT COUNT(*) FROM information_schema.INNODB_TRX) AS PendingRequests, 
        (SELECT VARIABLE_VALUE FROM information_schema.GLOBAL_STATUS WHERE VARIABLE_NAME = 'Threads_running') AS CPUQueueLength 
        FROM information_schema.SCHEMATA;
        "
      register: db_health
      ignore_errors: yes

    - name: Check for Deadlocks
      shell: |
        mysql -h {{ mysql_host }} -u {{ mysql_user }} -p{{ mysql_password }} -e "
        SELECT COUNT(*) AS Deadlocks 
        FROM information_schema.INNODB_LOCKS 
        WHERE lock_trx_id IN (SELECT blocking_trx_id FROM information_schema.INNODB_LOCK_WAITS);
        "
      register: deadlocks
      ignore_errors: yes

    - name: Get MySQL Scheduled Events
      shell: |
        mysql -h {{ mysql_host }} -u {{ mysql_user }} -p{{ mysql_password }} -e "
        SELECT EVENT_NAME AS EventName, 
        EVENT_SCHEMA AS DatabaseName, 
        STATUS AS Status, 
        LAST_EXECUTED AS LastExecuted 
        FROM information_schema.EVENTS;
        "
      register: scheduled_events
      ignore_errors: yes

    - name: Display Database Space Utilization
      debug:
        msg: |
          📊 Database Space Utilization:
          {{ db_space.stdout }}

    - name: Display Database Health
      debug:
        msg: |
          🩺 Database Health Check:
          {{ db_health.stdout }}

    - name: Display Deadlocks
      debug:
        msg: |
          🚨 Deadlocks:
          {{ deadlocks.stdout }}

    - name: Display Scheduled Events
      debug:
        msg: |
          🛠 MySQL Scheduled Events:
          {{ scheduled_events.stdout }}
