---
- name: MySQL Health Check Playbook
  hosts: localhost
  become: yes
  vars:
    mysql_user: "mysqlauto"
    mysql_password: "mysqlAutomation"
    
  tasks:
    - name: Check MySQL Service Status
      service_facts:
      register: mysql_status

    - name: Get Database Sizes
      mysql_query:
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
        query: |
          SELECT 
            table_schema AS 'Database',
            ROUND(SUM(data_length + index_length) / 1024 / 1024, 2) AS 'Size_MB'
          FROM information_schema.tables
          GROUP BY table_schema;
      register: db_sizes

    - name: Check for Deadlocks
      mysql_query:
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
        query: |
          SHOW ENGINE INNODB STATUS\G
      register: deadlock_status

    - name: Get Running Processes
      mysql_query:
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
        query: |
          SELECT 
            id,
            user,
            host,
            db,
            command,
            time,
            state,
            info
          FROM information_schema.processlist
          WHERE command != 'Sleep';
      register: process_list

    - name: Check Event Scheduler Status
      mysql_query:
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
        query: |
          SELECT 
            event_name,
            status,
            last_executed,
            starts,
            ends
          FROM information_schema.events;
      register: event_status

    - name: Create Health Report
      template:
        src: mysql_health_report.j2
        dest: "/tmp/mysql_health_report_{{ ansible_date_time.date }}.txt"

    - name: Display Health Report
      debug:
        msg: "MySQL health report has been generated at /tmp/mysql_health_report_{{ ansible_date_time.date }}.txt"
