---
- name: Check MySQL database space
  hosts: localhost
  become: yes
  gather_facts: no
  tasks:
    - name: Check MySQL Database space
      mysql_db:
        login_user: "mysqlauto"
        login_password: "mysqlAutomation"
        login_host: "10.112.0.11"
        query: "SELECT table_schema 'DB Name', SUM(data_length + index_length) / 1024 / 1024 'DB Size in MB' FROM information_schema.tables GROUP BY table_schema;"
      register: mysql_db_space

    - name: Display MySQL space usage
      debug:
        var: mysql_db_space.query_result
