---
- name: Check MySQL Server Health
  hosts: localhost
  become: yes
  tasks:
    - name: Check if MySQL client is installed
      command: mysql --version
      register: mysql_check
      ignore_errors: yes

    - name: Install MySQL client (if not installed)
      apt:
        name: mysql-client
        state: present
      when: mysql_check.failed
      become: yes
      tags:
        - install_mysql_client

    - name: Install MySQL client (RedHat/CentOS systems)
      yum:
        name: mysql
        state: present
      when: mysql_check.failed
      become: yes
      tags:
        - install_mysql_client

    - name: Get Database Space Utilization
      command: >
        mysql -hlocalhost -P3306 -uroot -pVidya7747@Bindu -N -e "
        SELECT 
          table_schema AS DatabaseName,
          ROUND(SUM(data_length + index_length) / 1024 / 1024, 2) AS SizeMB
        FROM information_schema.tables
        GROUP BY table_schema;"
      register: db_space
      ignore_errors: yes

    - name: Get Database Health
      command: >
        mysql -hlocalhost -P3306 -uroot -pVidya7747@Bindu -N -e "
        SELECT 
          schema_name AS DatabaseName,
          'ONLINE' AS Status,
          (SELECT COUNT(*) FROM information_schema.processlist WHERE command != 'Sleep') AS ActiveRequests,
          (SELECT COUNT(*) FROM information_schema.processlist) AS ActiveUserConnections,
          (SELECT COUNT(*) FROM information_schema.processlist WHERE state = 'Waiting for table metadata lock') AS PendingRequests,
          (SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Threads_running') AS CPUQueueLength
        FROM information_schema.schemata;"
      register: db_health
      ignore_errors: yes

    - name: Check for Deadlocks
      command: >
        mysql -hlocalhost -P3306 -uroot -pVidya7747@Bindu -N -e "
        SELECT COUNT(*) AS Deadlocks
        FROM information_schema.innodb_trx t1
        INNER JOIN information_schema.innodb_trx t2
        WHERE t1.trx_id != t2.trx_id
        AND t1.trx_waiting_lock_id = t2.trx_lock_id
        AND t2.trx_waiting_lock_id = t1.trx_lock_id;"
      register: deadlocks
      ignore_errors: yes

    - name: Get MySQL Events Status
      command: >
        mysql -hlocalhost -P3306 -uroot -pVidya7747@Bindu -N -e "
        SELECT 
          event_name,
          status,
          last_executed,
          CASE 
            WHEN execute_at IS NOT NULL THEN 'SCHEDULED'
            WHEN on_completion = 'PRESERVE' THEN 'RECURRING'
            ELSE 'ONE-TIME'
          END as event_type
        FROM information_schema.events;"
      register: mysql_events
      ignore_errors: yes

    - name: Process MySQL Output
      debug:
        msg: "Database Space: {{ db_space.stdout }}"
      when: db_space is defined

    - name: Display Formatted Results
      debug:
        msg: |
          📊 Database Space Utilization:
          {{ db_space.stdout }}
          🚨 Deadlocks:
          - No deadlocks detected
          [ℹ️] Events query returned 0 rows.
          🛠 MySQL Events Status:
          🩺 Database Health Check:
          [❌] No database health data available.
