---
- name: Check MySQL Server Health
  hosts: localhost
  gather_facts: no
  vars:
    mysql_host: "{{mysql_host}}"
    mysql_user: "{{mysql_user}}"
    mysql_password: "{{mysql_password}}"
    mysql_port: "{mysql_port}}"
 
  tasks:
    - name: Get Database Space Utilization
      community.mysql.mysql_query:
        login_host: "{{ mysql_host }}"
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
        login_port: "{{ mysql_port }}"
        query: |
          SELECT 
            table_schema AS DatabaseName,
            ROUND(SUM(data_length + index_length) / 1024 / 1024, 2) AS SizeMB
          FROM information_schema.tables 
          GROUP BY table_schema;
      register: db_space
      ignore_errors: yes

 
   
    - name: Process MySQL Output
      set_fact:
        db_space_fact: "{{ db_space.stdout_lines | map('split', '\t') | 
                          map('list') | map('dict', ['DatabaseName', 'SizeMB']) | list }}"
