---
- name: MySQL Server Health Check
  hosts: localhost
  become: yes
  vars:
    mysql_host: "10.112.0.11"   # Adjust as needed
    mysql_user: "mysqlauto"        # Use a MySQL user with appropriate permissions
    mysql_password: "mysqlAutomation"  # Optional if you want to provide the password
    ansible_ssh_private_key_file: r"C:\Users\ramakistu.vidya\Downloads\id_rsa 1"  # Path to your private key

  tasks:
    - name: Check MySQL database disk space
      command: "df -h /var/lib/mysql"  # Path to the MySQL data directory
      register: db_space
    - name: Display database space utilization
      debug:
        var: db_space.stdout_lines

    - name: Check MySQL database utilization
      mysql_db:
        login_host: "{{ mysql_host }}"
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
        state: query
        query: "SELECT table_schema AS 'Database', ROUND(SUM(data_length + index_length) / 1024 / 1024, 2) AS 'Size(MB)' FROM information_schema.tables GROUP BY table_schema;"
      register: db_utilization

    - name: Display database utilization
      debug:
        var: db_utilization.query_result

    - name: Check MySQL health status
      mysql_db:
        login_host: "{{ mysql_host }}"
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
        state: query
        query: "SHOW STATUS;"
      register: db_health_status

    - name: Display MySQL health status
      debug:
        var: db_health_status.query_result

    - name: Check for deadlocks in InnoDB
      mysql_db:
        login_host: "{{ mysql_host }}"
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
        state: query
        query: "SHOW ENGINE INNODB STATUS;"
      register: innodb_status

    - name: Display InnoDB status
      debug:
        var: innodb_status.query_result

    - name: Check for active MySQL jobs/threads
      mysql_db:
        login_host: "{{ mysql_host }}"
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
        state: query
        query: "SHOW PROCESSLIST;"
      register: process_list

    - name: Display MySQL process list
      debug:
        var: process_list.query_result
