---
- name: MySQL Database Health Check
  hosts: localhost
  connection: local
  vars:
    mysql_user: "mysqlauto"
    mysql_password: "mysqlAutomation"
    mysql_host: "10.112.0.10"
    mysql_db: "information_schema"

  tasks:
    - name: Check Database Space
      command: >
        mysql -h {{ mysql_host }} -u {{ mysql_user }} -p{{ mysql_password }} -e "
        SELECT table_schema AS 'Database', 
        ROUND(SUM(data_length + index_length) / 1024 / 1024, 2) AS 'Size (MB)' 
        FROM information_schema.TABLES 
        GROUP BY table_schema;"
      register: db_space

    - name: Display Database Space
      debug:
        var: db_space.stdout

    - name: Check Database Utilization
      command: >
        mysql -h {{ mysql_host }} -u {{ mysql_user }} -p{{ mysql_password }} -e "
        SHOW STATUS LIKE 'Threads_connected';
        SHOW STATUS LIKE 'Queries';
        SHOW STATUS LIKE 'Innodb_row_lock%';"
      register: db_utilization

    - name: Display Database Utilization
      debug:
        var: db_utilization.stdout

    - name: Check Database Health
      command: >
        mysql -h {{ mysql_host }} -u {{ mysql_user }} -p{{ mysql_password }} -e "
        SHOW ENGINE INNODB STATUS;"
      register: db_health

    - name: Display Database Health
      debug:
        var: db_health.stdout

    - name: Check for Deadlocks
      command: >
        mysql -h {{ mysql_host }} -u {{ mysql_user }} -p{{ mysql_password }} -e "
        SHOW ENGINE INNODB STATUS;"
      register: deadlocks

    - name: Display Deadlocks
      debug:
        var: deadlocks.stdout

    - name: Check for Job Activities
      command: >
        mysql -h {{ mysql_host }} -u {{ mysql_user }} -p{{ mysql_password }} -e "
        SELECT * FROM information_schema.EVENTS;"
      register: job_activities

    - name: Display Job Activities
      debug:
        var: job_activities.stdout
