---
- name: MySQL Health Check Playbook
  hosts: 20.55.88.203
  gather_facts: no
  become: no
  vars:
    mysql_host: "20.55.88.203"
    mysql_port: "3306"
    mysql_user: "mysqlauto"
    mysql_password: "mysqlAutomation"
    mysql_cmd: "/usr/bin/mysql -h{{ mysql_host }} -P{{ mysql_port }} -u{{ mysql_user }} -p{{ mysql_password }} -N -B"
  
  tasks:
    - name: Create timestamp
      set_fact:
        timestamp: "{{ lookup('pipe', 'date +%Y-%m-%d_%H-%M-%S') }}"

    - name: Get Database Sizes
      shell: |
        {{ mysql_cmd }} -e "
        SELECT CONCAT(table_schema, ',', 
          ROUND(SUM(data_length + index_length) / 1024 / 1024, 2)) 
        FROM information_schema.tables 
        GROUP BY table_schema;"
      register: db_sizes
      ignore_errors: yes

    - name: Get Running Processes
      shell: |
        {{ mysql_cmd }} -e "
        SELECT CONCAT(id, ',', user, ',', db, ',', command, ',', time, ',', state) 
        FROM information_schema.processlist
        WHERE command != 'Sleep';"
      register: process_list
      ignore_errors: yes

    - name: Get Lock Status
      shell: |
        {{ mysql_cmd }} -e "
        SELECT CONCAT(waiting_pid, ',', waiting_query, ',', blocking_pid, ',', blocking_query)
        FROM sys.innodb_lock_waits;"
      register: lock_status
      ignore_errors: yes

    - name: Get Server Status
      shell: |
        {{ mysql_cmd }} -e "SHOW GLOBAL STATUS WHERE 
        Variable_name IN ('Threads_connected', 'Threads_running', 'Questions', 'Queries', 'Uptime');"
      register: server_status
      ignore_errors: yes

    - name: Create Report Directory
      file:
        path: "./mysql_reports"
        state: directory
        mode: '0755'

    - name: Generate Health Report
      copy:
        content: |
          MySQL Health Report - {{ timestamp }}
          ================================================

          Connection Information
          ---------------------
          Host: {{ mysql_host }}
          Port: {{ mysql_port }}
          User: {{ mysql_user }}

          Database Space Utilization
          -------------------------
          {% if db_sizes.rc == 0 %}
          {% for line in db_sizes.stdout_lines %}
          Database: {{ line.split(',')[0] }}
          Size (MB): {{ line.split(',')[1] }}
          {% endfor %}
          {% else %}
          Failed to get database sizes
          Error: {{ db_sizes.stderr if db_sizes.stderr is defined else 'Unknown error' }}
          {% endif %}

          Running Processes
          ----------------
          {% if process_list.rc == 0 %}
          {% for line in process_list.stdout_lines %}
          {% set parts = line.split(',') %}
          ID: {{ parts[0] }}
          User: {{ parts[1] }}
          Database: {{ parts[2] }}
          Command: {{ parts[3] }}
          Time: {{ parts[4] }}
          State: {{ parts[5] }}
          {% endfor %}
          {% else %}
          Failed to get process list
          Error: {{ process_list.stderr if process_list.stderr is defined else 'Unknown error' }}
          {% endif %}

          Lock Information
          ---------------
          {% if lock_status.rc == 0 %}
          {% for line in lock_status.stdout_lines %}
          {% set parts = line.split(',') %}
          Waiting Process: {{ parts[0] }}
          Waiting Query: {{ parts[1] }}
          Blocking Process: {{ parts[2] }}
          Blocking Query: {{ parts[3] }}
          {% endfor %}
          {% else %}
          Failed to get lock status
          Error: {{ lock_status.stderr if lock_status.stderr is defined else 'Unknown error' }}
          {% endif %}

          Server Status
          -------------
          {% if server_status.rc == 0 %}
          {{ server_status.stdout }}
          {% else %}
          Failed to get server status
          Error: {{ server_status.stderr if server_status.stderr is defined else 'Unknown error' }}
          {% endif %}
        dest: "./mysql_reports/mysql_health_report_{{ timestamp }}.txt"
        mode: '0644'

    - name: Display Report Location
      debug:
        msg: "MySQL health report has been generated at ./mysql_reports/mysql_health_report_{{ timestamp }}.txt"
