---
- name: Check MySQL Server Health
  hosts: localhost
  gather_facts: no
  vars:
    mysql_host: "10.112.0.11"
    mysql_user: "mysqlauto"
    mysql_password: "mysqlAutomation"
    mysql_port: 3306
 
  tasks:
    - name: Get Database Space Utilization
      shell: |
        mysql -h{{ mysql_host }} -P{{ mysql_port }} -u{{ mysql_user }} -p{{ mysql_password }} -N -e "
        SELECT 
          table_schema AS DatabaseName,
          ROUND(SUM(data_length + index_length) / 1024 / 1024, 2) AS SizeMB
        FROM information_schema.tables 
        GROUP BY table_schema;"
      register: db_space
      ignore_errors: yes
 
   
    - name: Process MySQL Output
      set_fact:
        db_space_fact: "{{ db_space.stdout_lines | map('split', '\t') | 
                          map('list') | map('dict', ['DatabaseName', 'SizeMB']) | list }}"
