---
- name: MySQL Database Health Check
  hosts: localhost
  connection: local
  vars:
    mysql_user: "mysqlauto"
    mysql_password: "mysqlAutomation"
    mysql_host: "10.112.0.11"
    mysql_db: "information_schema"

  tasks:
    - name: Install community.mysql collection
      ansible.builtin.command:
        cmd: ansible-galaxy collection install community.mysql
      changed_when: false  # This prevents the task from always showing as "changed"

    - name: Check Database Space
      community.mysql.mysql_query:
        login_host: "{{ mysql_host }}"
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
        query: |
          SELECT table_schema AS 'Database', 
          ROUND(SUM(data_length + index_length) / 1024 / 1024, 2) AS 'Size (MB)' 
          FROM information_schema.TABLES 
          GROUP BY table_schema;
      register: db_space

    - name: Display Database Space
      debug:
        var: db_space.results

    - name: Check Database Utilization
      community.mysql.mysql_query:
        login_host: "{{ mysql_host }}"
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
        query: |
          SHOW STATUS LIKE 'Threads_connected';
          SHOW STATUS LIKE 'Queries';
          SHOW STATUS LIKE 'Innodb_row_lock%';
      register: db_utilization

    - name: Display Database Utilization
      debug:
        var: db_utilization.results

    - name: Check Database Health
      community.mysql.mysql_query:
        login_host: "{{ mysql_host }}"
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
        query: |
          SHOW ENGINE INNODB STATUS;
      register: db_health

    - name: Display Database Health
      debug:
        var: db_health.results

    - name: Check for Deadlocks
      community.mysql.mysql_query:
        login_host: "{{ mysql_host }}"
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
        query: |
          SHOW ENGINE INNODB STATUS;
      register: deadlocks

    - name: Display Deadlocks
      debug:
        var: deadlocks.results

    - name: Check for Job Activities
      community.mysql.mysql_query:
        login_host: "{{ mysql_host }}"
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
        query: |
          SELECT * FROM information_schema.EVENTS;
      register: job_activities

    - name: Display Job Activities
      debug:
        var: job_activities.results
