---
- name: MySQL Health Check and Monitoring
  hosts: localhost
  gather_facts: no  # Disable fact gathering
  vars:
    mysql_host: "10.112.0.11"
    mysql_database: "information_schema"
    mysql_username: "mysqlauto"
    mysql_password: "mysqlAutomation"
    mysql_port: "3306"

  tasks:
    - name: Install mysql-connector-python (if not already installed)
      pip:
        name: mysql-connector-python
        state: present
      become: no  # Run without elevated privileges

    - name: Check database space utilization
      script: "C:\Users\ramakistu.vidya\OneDrive - ascendion\Desktop\p1\check_db_space.py"
      register: db_space

    - name: Display database space utilization
      debug:
        msg: "{{ db_space.stdout }}"

    - name: Check for deadlocks in MySQL
      script: "C:\Users\ramakistu.vidya\OneDrive - ascendion\Desktop\p1\check_deadlocks.py"
      register: deadlocks

    - name: Display deadlock information
      debug:
        msg: "{{ deadlocks.stdout }}"

    - name: Check MySQL event scheduler activities
      script: "C:\Users\ramakistu.vidya\OneDrive - ascendion\Desktop\p1\check_job_activities.py"
      register: job_activities

    - name: Display MySQL event activities
      debug:
        msg: "{{ job_activities.stdout }}"

    - name: Check MySQL health status
      script: "C:\Users\ramakistu.vidya\OneDrive - ascendion\Desktop\p1\check_db_health.py"
      register: db_health

    - name: Display database health check
      debug:
        msg: "{{ db_health.stdout }}"

    - name: Check MySQL version
      script: "C:\Users\ramakistu.vidya\OneDrive - ascendion\Desktop\p1\check_mysql_version.py"
      register: mysql_version

    - name: Display MySQL version
      debug:
        msg: "{{ mysql_version.stdout }}"
