---
- name: MySQL Health Check Playbook
  hosts: 10.112.0.11
  gather_facts: no
  become: no
  vars:
    mysql_host: "20.55.88.203"
    mysql_port: "3306"
    mysql_user: "mysqlauto"
    mysql_password: "mysqlAutomation"
  
  tasks:
    - name: Find MySQL client
      shell: "which mysql || echo ''"
      register: mysql_path
      ignore_errors: yes

    - name: Set MySQL command
      set_fact:
        mysql_cmd: "{{ mysql_path.stdout if mysql_path.stdout != '' else 'mysql' }} -h{{ mysql_host }} -P{{ mysql_port }} -u{{ mysql_user }} -p{{ mysql_password }} -N -B"

    - name: Create timestamp
      set_fact:
        timestamp: "{{ lookup('pipe', 'date +%Y-%m-%d_%H-%M-%S') }}"

    - name: Test MySQL Connection
      shell: "{{ mysql_cmd }} -e 'SELECT VERSION();'"
      register: mysql_version
      ignore_errors: yes

    - name: Initialize empty variables
      set_fact:
        db_sizes: {"stdout": "", "stderr": "Query not executed", "rc": -1}
        process_list: {"stdout": "", "stderr": "Query not executed", "rc": -1}
        server_status: {"stdout": "", "stderr": "Query not executed", "rc": -1}
        table_status: {"stdout": "", "stderr": "Query not executed", "rc": -1}

    - name: Get Database Sizes
      shell: |
        {{ mysql_cmd }} -e "
        SELECT CONCAT(table_schema, ',', 
          ROUND(SUM(data_length + index_length) / 1024 / 1024, 2)) 
        FROM information_schema.tables 
        GROUP BY table_schema;"
      register: db_sizes
      when: mysql_version.rc is defined and mysql_version.rc == 0
      ignore_errors: yes

    - name: Get Running Processes
      shell: |
        {{ mysql_cmd }} -e "
        SELECT CONCAT(id, ',', user, ',', db, ',', time, ',', state) 
        FROM information_schema.processlist
        WHERE command != 'Sleep';"
      register: process_list
      when: mysql_version.rc is defined and mysql_version.rc == 0
      ignore_errors: yes

    - name: Get Server Status
      shell: |
        {{ mysql_cmd }} -e "
        SHOW GLOBAL STATUS WHERE Variable_name IN 
        ('Threads_connected', 'Threads_running', 'Questions', 'Uptime');"
      register: server_status
      when: mysql_version.rc is defined and mysql_version.rc == 0
      ignore_errors: yes

    - name: Get Table Status
      shell: |
        {{ mysql_cmd }} -e "
        SELECT CONCAT(table_schema, ',', table_name, ',', 
          engine, ',', IFNULL(table_rows, 'N/A'), ',',
          ROUND(data_length/1024/1024, 2))
        FROM information_schema.tables 
        WHERE table_schema NOT IN ('information_schema', 'performance_schema', 'mysql')
        ORDER BY data_length DESC LIMIT 10;"
      register: table_status
      when: mysql_version.rc is defined and mysql_version.rc == 0
      ignore_errors: yes

    - name: Create Report Directory
      file:
        path: "./mysql_reports"
        state: directory
        mode: '0755'

    - name: Generate Health Report
      copy:
        content: |
          MySQL Health Report - {{ timestamp }}
          ================================================

          Connection Information
          ---------------------
          Host: {{ mysql_host }}
          Port: {{ mysql_port }}
          MySQL Client: {{ mysql_path.stdout if mysql_path.stdout != '' else 'Not found in PATH' }}
          Connection Test: {{ 'Success' if mysql_version.rc is defined and mysql_version.rc == 0 else 'Failed - ' + mysql_version.stderr | default('Unknown error') }}

          {% if mysql_version.rc is defined and mysql_version.rc == 0 %}
          Database Space Utilization
          -------------------------
          {% if db_sizes.stdout_lines | default([]) | length > 0 %}
          {% for line in db_sizes.stdout_lines %}
          {% set parts = line.split(',') %}
          Database: {{ parts[0] }}
          Size (MB): {{ parts[1] }}
          {% endfor %}
          {% else %}
          No database size information available
          {% endif %}

          Top 10 Largest Tables
          --------------------
          {% if table_status.stdout_lines | default([]) | length > 0 %}
          {% for line in table_status.stdout_lines %}
          {% set parts = line.split(',') %}
          Schema: {{ parts[0] }}
          Table: {{ parts[1] }}
          Engine: {{ parts[2] }}
          Rows: {{ parts[3] }}
          Size (MB): {{ parts[4] }}
          {% endfor %}
          {% else %}
          No table status information available
          {% endif %}

          Running Processes
          ----------------
          {% if process_list.stdout_lines | default([]) | length > 0 %}
          {% for line in process_list.stdout_lines %}
          {% set parts = line.split(',') %}
          ID: {{ parts[0] }}
          User: {{ parts[1] }}
          Database: {{ parts[2] }}
          Time: {{ parts[3] }}
          State: {{ parts[4] }}
          {% endfor %}
          {% else %}
          No active processes
          {% endif %}

          Server Status
          -------------
          {% if server_status.stdout_lines | default([]) | length > 0 %}
          {{ server_status.stdout }}
          {% else %}
          No server status information available
          {% endif %}

          {% else %}
          ERROR: Could not connect to MySQL server
          Possible reasons:
          1. MySQL client is not installed
          2. MySQL server is not accessible
          3. Invalid credentials
          4. Network connectivity issues

          Please ensure:
          1. MySQL client is installed
          2. The server is running and accessible
          3. The credentials are correct
          4. Network connectivity is available
          {% endif %}
        dest: "./mysql_reports/mysql_health_report_{{ timestamp }}.txt"
        mode: '0644'

    - name: Display Report Location
      debug:
        msg: "MySQL health report has been generated at ./mysql_reports/mysql_health_report_{{ timestamp }}.txt"
